"""HTML invoice generation for marketplace orders and subscription payments."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Optional


def generate_order_invoice_html(order, business=None) -> str:
    """Invoice for a paid marketplace order (M-Pesa)."""
    shop = business.name if business else "Duka Yetu Seller"
    shop_email = getattr(business, "email", "") or ""
    shop_phone = getattr(business, "phone", "") or ""
    items = order.items or []
    rows = ""
    for item in items:
        rows += f"""
        <tr>
          <td style="padding:8px;border-bottom:1px solid #eee">{item.get('name','')}</td>
          <td style="padding:8px;border-bottom:1px solid #eee;text-align:center">{item.get('quantity',1)}</td>
          <td style="padding:8px;border-bottom:1px solid #eee;text-align:right">KES {item.get('unit_price','0')}</td>
          <td style="padding:8px;border-bottom:1px solid #eee;text-align:right">KES {item.get('subtotal','0')}</td>
        </tr>
        """
    paid_at = order.paid_at or order.created_at or datetime.utcnow()
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Invoice {order.order_number}</title></head>
<body style="font-family:Arial,sans-serif;color:#111;max-width:720px;margin:24px auto;padding:0 16px">
  <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:24px">
    <div>
      <h1 style="margin:0;font-size:22px">INVOICE</h1>
      <p style="margin:4px 0;color:#666">{order.order_number}</p>
    </div>
    <div style="text-align:right">
      <strong>{shop}</strong><br>
      {shop_phone}<br>
      {shop_email}
    </div>
  </div>
  <div style="display:flex;justify-content:space-between;margin-bottom:20px;gap:16px">
    <div>
      <p style="margin:0;color:#666;font-size:12px;text-transform:uppercase">Bill To</p>
      <p style="margin:4px 0"><strong>{order.customer_name}</strong><br>
      {order.customer_phone}<br>
      {order.customer_email or ""}<br>
      {order.delivery_address or ""}</p>
    </div>
    <div style="text-align:right">
      <p style="margin:0;color:#666;font-size:12px">Date</p>
      <p style="margin:4px 0">{paid_at.strftime('%Y-%m-%d %H:%M')}</p>
      <p style="margin:8px 0 0;color:#666;font-size:12px">Payment</p>
      <p style="margin:4px 0">M-Pesa · {order.mpesa_receipt_number or order.payment_status}</p>
    </div>
  </div>
  <table style="width:100%;border-collapse:collapse">
    <thead>
      <tr style="background:#f5f5f5">
        <th style="padding:10px 8px;text-align:left">Item</th>
        <th style="padding:10px 8px;text-align:center">Qty</th>
        <th style="padding:10px 8px;text-align:right">Unit</th>
        <th style="padding:10px 8px;text-align:right">Amount</th>
      </tr>
    </thead>
    <tbody>{rows}</tbody>
  </table>
  <div style="margin-top:16px;text-align:right">
    <p>Subtotal: <strong>KES {order.subtotal}</strong></p>
    <p style="font-size:18px">Total: <strong>KES {order.total_amount}</strong></p>
  </div>
  <p style="margin-top:32px;font-size:12px;color:#888">Generated by Duka Yetu · Powered by M-Pesa</p>
</body></html>"""


def generate_subscription_invoice_html(payment, business=None) -> str:
    """Invoice for a completed platform subscription M-Pesa payment."""
    snap = payment.cart_snapshot or {}
    plan = snap.get("plan") or "Plan"
    cycle = snap.get("billing_cycle") or "monthly"
    shop = business.name if business else "Business"
    email = getattr(business, "email", "") or ""
    date = payment.completed_at or payment.created_at or datetime.utcnow()
    receipt = payment.mpesa_receipt_number or payment.id
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Invoice SUB-{receipt}</title></head>
<body style="font-family:Arial,sans-serif;color:#111;max-width:720px;margin:24px auto;padding:0 16px">
  <h1 style="font-size:22px">Subscription Invoice</h1>
  <p style="color:#666">Invoice #SUB-{str(payment.id)[:8].upper()}</p>
  <div style="display:flex;justify-content:space-between;margin:24px 0">
    <div>
      <p style="margin:0;color:#666;font-size:12px">BILLED TO</p>
      <p><strong>{shop}</strong><br>{email}</p>
    </div>
    <div style="text-align:right">
      <p style="margin:0;color:#666;font-size:12px">DATE</p>
      <p>{date.strftime('%Y-%m-%d %H:%M')}</p>
      <p style="margin:8px 0 0;color:#666;font-size:12px">PAYMENT</p>
      <p>M-Pesa · {payment.mpesa_receipt_number or 'PAID'}</p>
    </div>
  </div>
  <table style="width:100%;border-collapse:collapse">
    <thead><tr style="background:#f5f5f5">
      <th style="padding:10px;text-align:left">Description</th>
      <th style="padding:10px;text-align:right">Amount</th>
    </tr></thead>
    <tbody>
      <tr>
        <td style="padding:10px;border-bottom:1px solid #eee">Duka Yetu {plan} plan ({cycle})</td>
        <td style="padding:10px;border-bottom:1px solid #eee;text-align:right">KES {payment.amount}</td>
      </tr>
    </tbody>
  </table>
  <p style="text-align:right;font-size:18px;margin-top:16px">Total paid: <strong>KES {payment.amount}</strong></p>
  <p style="margin-top:32px;font-size:12px;color:#888">Duka Yetu Platform · M-Pesa invoice</p>
</body></html>"""


def generate_feature_invoice_html(payment: Any, product_name: str, business=None) -> str:
    shop = business.name if business else "Business"
    date = payment.completed_at or payment.created_at or datetime.utcnow()
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Feature Invoice</title></head>
<body style="font-family:Arial,sans-serif;max-width:720px;margin:24px auto;padding:0 16px">
  <h1>Featured Placement Invoice</h1>
  <p>{shop} · {date.strftime('%Y-%m-%d')}</p>
  <p>Product featured: <strong>{product_name}</strong></p>
  <p>Amount: <strong>KES {payment.amount}</strong></p>
  <p>M-Pesa: {payment.mpesa_receipt_number or 'PAID'}</p>
</body></html>"""
