"""HTML invoice generation for marketplace orders and subscription payments."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Optional


def generate_order_invoice_html(order, business=None) -> str:
    """Invoice for a paid marketplace order (M-Pesa)."""
    shop = business.name if business else "Duka Yetu Seller"
    shop_email = getattr(business, "email", "") or ""
    shop_phone = getattr(business, "phone", "") or ""
    items = order.items or []
    rows = ""
    for item in items:
        rows += f"""
        <tr>
          <td style="padding:8px;border-bottom:1px solid #eee">{item.get('name','')}</td>
          <td style="padding:8px;border-bottom:1px solid #eee;text-align:center">{item.get('quantity',1)}</td>
          <td style="padding:8px;border-bottom:1px solid #eee;text-align:right">KES {item.get('unit_price','0')}</td>
          <td style="padding:8px;border-bottom:1px solid #eee;text-align:right">KES {item.get('subtotal','0')}</td>
        </tr>
        """
    paid_at = order.paid_at or order.created_at or datetime.utcnow()
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Invoice {order.order_number}</title></head>
<body style="font-family:Arial,sans-serif;color:#111;max-width:720px;margin:24px auto;padding:0 16px">
  <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:24px">
    <div>
      <h1 style="margin:0;font-size:22px">INVOICE</h1>
      <p style="margin:4px 0;color:#666">{order.order_number}</p>
    </div>
    <div style="text-align:right">
      <strong>{shop}</strong><br>
      {shop_phone}<br>
      {shop_email}
    </div>
  </div>
  <div style="display:flex;justify-content:space-between;margin-bottom:20px;gap:16px">
    <div>
      <p style="margin:0;color:#666;font-size:12px;text-transform:uppercase">Bill To</p>
      <p style="margin:4px 0"><strong>{order.customer_name}</strong><br>
      {order.customer_phone}<br>
      {order.customer_email or ""}<br>
      {order.delivery_address or ""}</p>
    </div>
    <div style="text-align:right">
      <p style="margin:0;color:#666;font-size:12px">Date</p>
      <p style="margin:4px 0">{paid_at.strftime('%Y-%m-%d %H:%M')}</p>
      <p style="margin:8px 0 0;color:#666;font-size:12px">Payment</p>
      <p style="margin:4px 0">M-Pesa · {order.mpesa_receipt_number or order.payment_status}</p>
    </div>
  </div>
  <table style="width:100%;border-collapse:collapse">
    <thead>
      <tr style="background:#f5f5f5">
        <th style="padding:10px 8px;text-align:left">Item</th>
        <th style="padding:10px 8px;text-align:center">Qty</th>
        <th style="padding:10px 8px;text-align:right">Unit</th>
        <th style="padding:10px 8px;text-align:right">Amount</th>
      </tr>
    </thead>
    <tbody>{rows}</tbody>
  </table>
  <div style="margin-top:16px;text-align:right">
    <p>Subtotal: <strong>KES {order.subtotal}</strong></p>
    <p style="font-size:18px">Total: <strong>KES {order.total_amount}</strong></p>
  </div>
  <p style="margin-top:32px;font-size:12px;color:#888">Generated by Duka Yetu · Powered by M-Pesa</p>
</body></html>"""


def generate_subscription_invoice_html(payment, business=None) -> str:
    """Invoice for a completed platform subscription M-Pesa payment."""
    snap = payment.cart_snapshot or {}
    plan = snap.get("plan") or "Plan"
    cycle = snap.get("billing_cycle") or "monthly"
    shop = business.name if business else "Business"
    email = getattr(business, "email", "") or ""
    date = payment.completed_at or payment.created_at or datetime.utcnow()
    receipt = payment.mpesa_receipt_number or payment.id
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Invoice SUB-{receipt}</title></head>
<body style="font-family:Arial,sans-serif;color:#111;max-width:720px;margin:24px auto;padding:0 16px">
  <h1 style="font-size:22px">Subscription Invoice</h1>
  <p style="color:#666">Invoice #SUB-{str(payment.id)[:8].upper()}</p>
  <div style="display:flex;justify-content:space-between;margin:24px 0">
    <div>
      <p style="margin:0;color:#666;font-size:12px">BILLED TO</p>
      <p><strong>{shop}</strong><br>{email}</p>
    </div>
    <div style="text-align:right">
      <p style="margin:0;color:#666;font-size:12px">DATE</p>
      <p>{date.strftime('%Y-%m-%d %H:%M')}</p>
      <p style="margin:8px 0 0;color:#666;font-size:12px">PAYMENT</p>
      <p>M-Pesa · {payment.mpesa_receipt_number or 'PAID'}</p>
    </div>
  </div>
  <table style="width:100%;border-collapse:collapse">
    <thead><tr style="background:#f5f5f5">
      <th style="padding:10px;text-align:left">Description</th>
      <th style="padding:10px;text-align:right">Amount</th>
    </tr></thead>
    <tbody>
      <tr>
        <td style="padding:10px;border-bottom:1px solid #eee">Duka Yetu {plan} plan ({cycle})</td>
        <td style="padding:10px;border-bottom:1px solid #eee;text-align:right">KES {payment.amount}</td>
      </tr>
    </tbody>
  </table>
  <p style="text-align:right;font-size:18px;margin-top:16px">Total paid: <strong>KES {payment.amount}</strong></p>
  <p style="margin-top:32px;font-size:12px;color:#888">Duka Yetu Platform · M-Pesa invoice</p>
</body></html>"""


def generate_platform_subscription_invoice_html(
    business,
    *,
    plan: str,
    amount: float,
    billing_cycle: str = "monthly",
    invoice_number: str,
    period_label: str,
) -> str:
    """End-of-month subscription invoice generated by super admin for a business."""
    date = datetime.utcnow()
    shop = getattr(business, "name", "Business")
    email = getattr(business, "email", "") or ""
    phone = getattr(business, "phone", "") or ""
    owner = getattr(business, "owner_name", "") or ""
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Invoice {invoice_number}</title></head>
<body style="font-family:Arial,sans-serif;color:#111;max-width:720px;margin:24px auto;padding:0 16px">
  <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:24px">
    <div>
      <h1 style="margin:0;font-size:22px">SUBSCRIPTION INVOICE</h1>
      <p style="margin:4px 0;color:#666">{invoice_number}</p>
    </div>
    <div style="text-align:right">
      <strong>Duka Yetu Platform</strong><br>
      Billing · SaaS subscription
    </div>
  </div>
  <div style="display:flex;justify-content:space-between;margin-bottom:20px;gap:16px">
    <div>
      <p style="margin:0;color:#666;font-size:12px;text-transform:uppercase">Bill To</p>
      <p style="margin:4px 0"><strong>{shop}</strong><br>
      {owner}<br>{phone}<br>{email}</p>
    </div>
    <div style="text-align:right">
      <p style="margin:0;color:#666;font-size:12px">Invoice date</p>
      <p style="margin:4px 0">{date.strftime('%Y-%m-%d')}</p>
      <p style="margin:8px 0 0;color:#666;font-size:12px">Period</p>
      <p style="margin:4px 0">{period_label}</p>
    </div>
  </div>
  <table style="width:100%;border-collapse:collapse">
    <thead>
      <tr style="background:#f5f5f5">
        <th style="padding:10px 8px;text-align:left">Description</th>
        <th style="padding:10px 8px;text-align:right">Amount</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td style="padding:10px 8px;border-bottom:1px solid #eee">
          Duka Yetu {plan} plan ({billing_cycle}) — platform subscription
        </td>
        <td style="padding:10px 8px;border-bottom:1px solid #eee;text-align:right">KES {amount:,.2f}</td>
      </tr>
    </tbody>
  </table>
  <p style="text-align:right;font-size:18px;margin-top:16px">Amount due: <strong>KES {amount:,.2f}</strong></p>
  <p style="margin-top:24px;font-size:13px;color:#444">
    Please settle via M-Pesa or your preferred method. Contact support if you have questions.
  </p>
  <p style="margin-top:32px;font-size:12px;color:#888">Generated by Duka Yetu Super Admin</p>
</body></html>"""


def generate_feature_invoice_html(payment: Any, product_name: str, business=None) -> str:
    shop = business.name if business else "Business"
    date = payment.completed_at or payment.created_at or datetime.utcnow()
    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Feature Invoice</title></head>
<body style="font-family:Arial,sans-serif;max-width:720px;margin:24px auto;padding:0 16px">
  <h1>Featured Placement Invoice</h1>
  <p>{shop} · {date.strftime('%Y-%m-%d')}</p>
  <p>Product featured: <strong>{product_name}</strong></p>
  <p>Amount: <strong>KES {payment.amount}</strong></p>
  <p>M-Pesa: {payment.mpesa_receipt_number or 'PAID'}</p>
</body></html>"""


def _pdf_text(value: Any) -> str:
    return ("" if value is None else str(value)).encode("latin-1", "replace").decode("latin-1")


def _new_pdf():
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()
    return pdf


def _pdf_header(pdf, title: str, subtitle: str, right_lines: list[str]) -> None:
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, _pdf_text(title), ln=1)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(90, 90, 90)
    pdf.cell(0, 6, _pdf_text(subtitle), ln=1)
    pdf.set_text_color(17, 17, 17)
    y = pdf.get_y()
    pdf.set_xy(120, 18)
    pdf.set_font("Helvetica", "", 10)
    for line in right_lines:
        pdf.cell(80, 5, _pdf_text(line), ln=1, align="R")
        pdf.set_x(120)
    pdf.set_y(max(y, pdf.get_y()) + 8)


def generate_order_invoice_pdf(order, business=None) -> bytes:
    pdf = _new_pdf()
    shop = getattr(business, "name", None) or "Duka Yetu Seller"
    shop_email = getattr(business, "email", "") or ""
    shop_phone = getattr(business, "phone", "") or ""
    paid_at = order.paid_at or order.created_at or datetime.utcnow()
    _pdf_header(
        pdf,
        "INVOICE",
        order.order_number,
        [shop, shop_phone, shop_email],
    )
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(95, 6, "BILL TO", ln=0)
    pdf.cell(95, 6, "PAYMENT", ln=1)
    pdf.set_font("Helvetica", "", 10)
    left = f"{order.customer_name}\n{order.customer_phone}\n{order.customer_email or ''}\n{order.delivery_address or ''}"
    right = f"{paid_at.strftime('%Y-%m-%d %H:%M')}\nM-Pesa · {order.mpesa_receipt_number or order.payment_status}"
    start_y = pdf.get_y()
    pdf.multi_cell(95, 5, _pdf_text(left))
    after_left = pdf.get_y()
    pdf.set_xy(105, start_y)
    pdf.multi_cell(95, 5, _pdf_text(right))
    pdf.set_y(max(after_left, pdf.get_y()) + 6)

    pdf.set_fill_color(245, 245, 245)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(80, 8, "Item", border=0, fill=True)
    pdf.cell(25, 8, "Qty", border=0, fill=True, align="C")
    pdf.cell(40, 8, "Unit", border=0, fill=True, align="R")
    pdf.cell(45, 8, "Amount", border=0, fill=True, align="R", ln=1)
    pdf.set_font("Helvetica", "", 10)
    for item in order.items or []:
        pdf.cell(80, 8, _pdf_text(item.get("name", ""))[:40])
        pdf.cell(25, 8, _pdf_text(item.get("quantity", 1)), align="C")
        pdf.cell(40, 8, _pdf_text(f"KES {item.get('unit_price', '0')}"), align="R")
        pdf.cell(45, 8, _pdf_text(f"KES {item.get('subtotal', '0')}"), align="R", ln=1)
    pdf.ln(4)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 6, _pdf_text(f"Subtotal: KES {order.subtotal}"), ln=1, align="R")
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, _pdf_text(f"Total: KES {order.total_amount}"), ln=1, align="R")
    pdf.ln(10)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 5, "Generated by Duka Yetu · Powered by M-Pesa", ln=1)
    return bytes(pdf.output())


def generate_subscription_invoice_pdf(payment, business=None) -> bytes:
    pdf = _new_pdf()
    snap = payment.cart_snapshot or {}
    plan = snap.get("plan") or "Plan"
    cycle = snap.get("billing_cycle") or "monthly"
    shop = getattr(business, "name", None) or "Business"
    email = getattr(business, "email", "") or ""
    date = payment.completed_at or payment.created_at or datetime.utcnow()
    _pdf_header(pdf, "SUBSCRIPTION INVOICE", f"SUB-{str(payment.id)[:8].upper()}", [shop, email])
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, _pdf_text(f"Date: {date.strftime('%Y-%m-%d %H:%M')}"), ln=1)
    pdf.cell(0, 6, _pdf_text(f"Payment: M-Pesa · {payment.mpesa_receipt_number or 'PAID'}"), ln=1)
    pdf.ln(4)
    pdf.set_fill_color(245, 245, 245)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(140, 8, "Description", fill=True)
    pdf.cell(50, 8, "Amount", fill=True, align="R", ln=1)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(140, 8, _pdf_text(f"Duka Yetu {plan} plan ({cycle})"))
    pdf.cell(50, 8, _pdf_text(f"KES {payment.amount}"), align="R", ln=1)
    pdf.ln(6)
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, _pdf_text(f"Total paid: KES {payment.amount}"), ln=1, align="R")
    return bytes(pdf.output())


def generate_platform_subscription_invoice_pdf(
    business,
    *,
    plan: str,
    amount: float,
    billing_cycle: str = "monthly",
    invoice_number: str,
    period_label: str,
) -> bytes:
    pdf = _new_pdf()
    date = datetime.utcnow()
    shop = getattr(business, "name", "Business")
    email = getattr(business, "email", "") or ""
    phone = getattr(business, "phone", "") or ""
    owner = getattr(business, "owner_name", "") or ""
    _pdf_header(
        pdf,
        "SUBSCRIPTION INVOICE",
        invoice_number,
        ["Duka Yetu Platform", "Billing · SaaS subscription"],
    )
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(0, 6, "BILL TO", ln=1)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 5, _pdf_text(f"{shop}\n{owner}\n{phone}\n{email}"))
    pdf.cell(0, 6, _pdf_text(f"Invoice date: {date.strftime('%Y-%m-%d')}"), ln=1)
    pdf.cell(0, 6, _pdf_text(f"Period: {period_label}"), ln=1)
    pdf.ln(4)
    pdf.set_fill_color(245, 245, 245)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(140, 8, "Description", fill=True)
    pdf.cell(50, 8, "Amount", fill=True, align="R", ln=1)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(140, 8, _pdf_text(f"Duka Yetu {plan} plan ({billing_cycle})"))
    pdf.cell(50, 8, _pdf_text(f"KES {amount:,.2f}"), align="R", ln=1)
    pdf.ln(6)
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, _pdf_text(f"Amount due: KES {amount:,.2f}"), ln=1, align="R")
    pdf.ln(8)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(80, 80, 80)
    pdf.multi_cell(0, 5, "Please settle via M-Pesa or your preferred method.")
    return bytes(pdf.output())


def pdf_attachment(content: bytes, filename: str):
    from fastapi.responses import Response

    return Response(
        content=content,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
